version: 2.1

orbs:
  go-jobs: palantir/go-jobs@0.6.0

image-version: &image-version "cimg/go:1.25.1-browsers"

checkout-path: &checkout-path
  path: /home/circleci/go/src/github.com/palantir/pkg

# Filter that matches all tags (will run on every build).
all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

# Filter that matches any branch besides primary branch and ignores all tags except for release candidates
pull-request-filter: &pull-request-filter
  filters:
    tags:
      only: /.*-rc.*/
    branches:
      ignore:
        - master

executors:
  standard-executor-bearertoken:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/bearertoken

  standard-executor-binary:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/binary

  standard-executor-boolean:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/boolean

  standard-executor-bytesbuffers:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/bytesbuffers

  standard-executor-cli:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/cli

  standard-executor-cobracli:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/cobracli

  standard-executor-datetime:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/datetime

  standard-executor-gittest:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/gittest

  standard-executor-httpclient:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/httpclient

  standard-executor-httpserver:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/httpserver

  standard-executor-matcher:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/matcher

  standard-executor-merge:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/merge

  standard-executor-metrics:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/metrics

  standard-executor-objmatcher:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/objmatcher

  standard-executor-pkgpath:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/pkgpath

  standard-executor-refreshable:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/refreshable

  standard-executor-retry:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/retry

  standard-executor-rid:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/rid

  standard-executor-safehttp:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/safehttp

  standard-executor-safejson:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/safejson

  standard-executor-safelong:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/safelong

  standard-executor-safeyaml:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/safeyaml

  standard-executor-signals:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/signals

  standard-executor-specdir:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/specdir

  standard-executor-tableprinter:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/tableprinter

  standard-executor-tlsconfig:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/tlsconfig

  standard-executor-transform:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/transform

  standard-executor-typenames:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/typenames

  standard-executor-uuid:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/uuid

  standard-executor-yamlpatch:
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    working_directory: /home/circleci/go/src/github.com/palantir/pkg/yamlpatch

# The set of jobs that should be run on every build
requires_jobs: &requires_jobs
  - bearertoken-verify
  - binary-verify
  - boolean-verify
  - bytesbuffers-verify
  - cli-verify
  - cobracli-verify
  - datetime-verify
  - gittest-verify
  - httpclient-verify
  - httpserver-verify
  - matcher-verify
  - merge-verify
  - metrics-verify
  - objmatcher-verify
  - pkgpath-verify
  - refreshable-verify
  - retry-verify
  - rid-verify
  - safehttp-verify
  - safejson-verify
  - safelong-verify
  - safeyaml-verify
  - signals-verify
  - specdir-verify
  - tableprinter-verify
  - tlsconfig-verify
  - transform-verify
  - typenames-verify
  - uuid-verify
  - yamlpatch-verify

jobs:
  verify-circleci:
    working_directory: /home/circleci/go/src/github.com/palantir/pkg
    docker:
      - image: *image-version
    environment:
      GOTOOLCHAIN: local
    resource_class: small
    steps:
      - checkout
      - run: go version
      - run: go run .circleci/generate.go .
      - run: diff  <(cat .circleci/config.yml) <(go run .circleci/generate.go .)

workflows:
  version: 2
  verify-test:
    jobs:
      - verify-circleci
      - go-jobs/circle_all:
          name: "circle-all"
          image: "busybox:1.36.1"
          requires: *requires_jobs
          <<: *pull-request-filter

      # bearertoken
      - go-jobs/godel_verify:
          name: bearertoken-verify
          executor: standard-executor-bearertoken
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # binary
      - go-jobs/godel_verify:
          name: binary-verify
          executor: standard-executor-binary
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # boolean
      - go-jobs/godel_verify:
          name: boolean-verify
          executor: standard-executor-boolean
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # bytesbuffers
      - go-jobs/godel_verify:
          name: bytesbuffers-verify
          executor: standard-executor-bytesbuffers
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # cli
      - go-jobs/godel_verify:
          name: cli-verify
          executor: standard-executor-cli
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # cobracli
      - go-jobs/godel_verify:
          name: cobracli-verify
          executor: standard-executor-cobracli
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # datetime
      - go-jobs/godel_verify:
          name: datetime-verify
          executor: standard-executor-datetime
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # gittest
      - go-jobs/godel_verify:
          name: gittest-verify
          executor: standard-executor-gittest
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # httpclient
      - go-jobs/godel_verify:
          name: httpclient-verify
          executor: standard-executor-httpclient
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # httpserver
      - go-jobs/godel_verify:
          name: httpserver-verify
          executor: standard-executor-httpserver
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # matcher
      - go-jobs/godel_verify:
          name: matcher-verify
          executor: standard-executor-matcher
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # merge
      - go-jobs/godel_verify:
          name: merge-verify
          executor: standard-executor-merge
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # metrics
      - go-jobs/godel_verify:
          name: metrics-verify
          executor: standard-executor-metrics
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # objmatcher
      - go-jobs/godel_verify:
          name: objmatcher-verify
          executor: standard-executor-objmatcher
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # pkgpath
      - go-jobs/godel_verify:
          name: pkgpath-verify
          executor: standard-executor-pkgpath
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # refreshable
      - go-jobs/godel_verify:
          name: refreshable-verify
          executor: standard-executor-refreshable
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # retry
      - go-jobs/godel_verify:
          name: retry-verify
          executor: standard-executor-retry
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # rid
      - go-jobs/godel_verify:
          name: rid-verify
          executor: standard-executor-rid
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # safehttp
      - go-jobs/godel_verify:
          name: safehttp-verify
          executor: standard-executor-safehttp
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # safejson
      - go-jobs/godel_verify:
          name: safejson-verify
          executor: standard-executor-safejson
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # safelong
      - go-jobs/godel_verify:
          name: safelong-verify
          executor: standard-executor-safelong
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # safeyaml
      - go-jobs/godel_verify:
          name: safeyaml-verify
          executor: standard-executor-safeyaml
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # signals
      - go-jobs/godel_verify:
          name: signals-verify
          executor: standard-executor-signals
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # specdir
      - go-jobs/godel_verify:
          name: specdir-verify
          executor: standard-executor-specdir
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # tableprinter
      - go-jobs/godel_verify:
          name: tableprinter-verify
          executor: standard-executor-tableprinter
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # tlsconfig
      - go-jobs/godel_verify:
          name: tlsconfig-verify
          executor: standard-executor-tlsconfig
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # transform
      - go-jobs/godel_verify:
          name: transform-verify
          executor: standard-executor-transform
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # typenames
      - go-jobs/godel_verify:
          name: typenames-verify
          executor: standard-executor-typenames
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # uuid
      - go-jobs/godel_verify:
          name: uuid-verify
          executor: standard-executor-uuid
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter

      # yamlpatch
      - go-jobs/godel_verify:
          name: yamlpatch-verify
          executor: standard-executor-yamlpatch
          setup_steps:
            - go-jobs/default_setup_steps:
                checkout_steps:
                  - checkout:
                      <<: *checkout-path
          <<: *all-tags-filter
