version: 2.1

orbs:
  go: palantir/go@0.0.29
  godel: palantir/godel@0.0.29

homepath: &homepath
  homepath: /home/circleci

gopath: &gopath
  gopath: /home/circleci/go

working_directory: &working_directory
  working_directory: /home/circleci/go/src/github.com/palantir/pkg

executors:
  circleci-go:
    docker:
      - image: cimg/go:1.16-browsers
    <<: *working_directory

jobs:
  verify-circleci:
    <<: *working_directory
    docker:
      - image: cimg/go:1.16-browsers
    resource_class: small
    steps:
      - checkout
      - run: go version
      - run: go run .circleci/generate.go .
      - run: diff  <(cat .circleci/config.yml) <(go run .circleci/generate.go .)
  circle-all:
    docker:
      - image: cimg/go:1.16-browsers
    resource_class: small
    steps:
      - run: echo "All required jobs run successfully"

workflows:
  version: 2
  verify-test:
    jobs:
      - verify-circleci
      - circle-all:
          requires: [ verify-circleci, bearertoken-verify, bearertoken-test-go-prev, binary-verify, binary-test-go-prev, boolean-verify, boolean-test-go-prev, bytesbuffers-verify, bytesbuffers-test-go-prev, cli-verify, cli-test-go-prev, cobracli-verify, cobracli-test-go-prev, datetime-verify, datetime-test-go-prev, gittest-verify, gittest-test-go-prev, httpclient-verify, httpclient-test-go-prev, httpserver-verify, httpserver-test-go-prev, matcher-verify, matcher-test-go-prev, merge-verify, merge-test-go-prev, metrics-verify, metrics-test-go-prev, objmatcher-verify, objmatcher-test-go-prev, pkgpath-verify, pkgpath-test-go-prev, refreshable-verify, refreshable-test-go-prev, retry-verify, retry-test-go-prev, rid-verify, rid-test-go-prev, safehttp-verify, safehttp-test-go-prev, safejson-verify, safejson-test-go-prev, safelong-verify, safelong-test-go-prev, safeyaml-verify, safeyaml-test-go-prev, signals-verify, signals-test-go-prev, specdir-verify, specdir-test-go-prev, tableprinter-verify, tableprinter-test-go-prev, tlsconfig-verify, tlsconfig-test-go-prev, transform-verify, transform-test-go-prev, typenames-verify, typenames-test-go-prev, uuid-verify, uuid-test-go-prev, yamlpatch-verify, yamlpatch-test-go-prev ]

      # bearertoken
      - godel/verify:
          name: bearertoken-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: bearertoken-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - bearertoken-verify

      # binary
      - godel/verify:
          name: binary-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: binary-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - binary-verify

      # boolean
      - godel/verify:
          name: boolean-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: boolean-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - boolean-verify

      # bytesbuffers
      - godel/verify:
          name: bytesbuffers-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: bytesbuffers-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - bytesbuffers-verify

      # cli
      - godel/verify:
          name: cli-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: cli-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - cli-verify

      # cobracli
      - godel/verify:
          name: cobracli-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: cobracli-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - cobracli-verify

      # datetime
      - godel/verify:
          name: datetime-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: datetime-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - datetime-verify

      # gittest
      - godel/verify:
          name: gittest-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: gittest-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - gittest-verify

      # httpclient
      - godel/verify:
          name: httpclient-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: httpclient-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - httpclient-verify

      # httpserver
      - godel/verify:
          name: httpserver-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: httpserver-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - httpserver-verify

      # matcher
      - godel/verify:
          name: matcher-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: matcher-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - matcher-verify

      # merge
      - godel/verify:
          name: merge-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: merge-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - merge-verify

      # metrics
      - godel/verify:
          name: metrics-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: metrics-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - metrics-verify

      # objmatcher
      - godel/verify:
          name: objmatcher-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: objmatcher-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - objmatcher-verify

      # pkgpath
      - godel/verify:
          name: pkgpath-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: pkgpath-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - pkgpath-verify

      # refreshable
      - godel/verify:
          name: refreshable-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: refreshable-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - refreshable-verify

      # retry
      - godel/verify:
          name: retry-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: retry-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - retry-verify

      # rid
      - godel/verify:
          name: rid-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: rid-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - rid-verify

      # safehttp
      - godel/verify:
          name: safehttp-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: safehttp-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - safehttp-verify

      # safejson
      - godel/verify:
          name: safejson-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: safejson-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - safejson-verify

      # safelong
      - godel/verify:
          name: safelong-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: safelong-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - safelong-verify

      # safeyaml
      - godel/verify:
          name: safeyaml-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: safeyaml-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - safeyaml-verify

      # signals
      - godel/verify:
          name: signals-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: signals-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - signals-verify

      # specdir
      - godel/verify:
          name: specdir-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: specdir-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - specdir-verify

      # tableprinter
      - godel/verify:
          name: tableprinter-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: tableprinter-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - tableprinter-verify

      # tlsconfig
      - godel/verify:
          name: tlsconfig-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: tlsconfig-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - tlsconfig-verify

      # transform
      - godel/verify:
          name: transform-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: transform-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - transform-verify

      # typenames
      - godel/verify:
          name: typenames-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: typenames-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - typenames-verify

      # uuid
      - godel/verify:
          name: uuid-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: uuid-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - uuid-verify

      # yamlpatch
      - godel/verify:
          name: yamlpatch-verify
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          include-tests: true
      - godel/test:
          name: yamlpatch-test-go-prev
          executor: circleci-go
          <<: *homepath
          <<: *gopath
          go-prev-version: 1
          requires:
            - yamlpatch-verify
