checkout-path: &checkout-path
  checkout-path: /go/src/github.com/palantir/pkg

version: 2.1

orbs:
  go: palantir/go@0.0.14
  godel: palantir/godel@0.0.14

jobs:
  verify-circleci:
    working_directory: /go/src/github.com/palantir/pkg
    docker:
      - image: "golang:1.13.4"
    steps:
      - checkout
      - run: go version
      - run: go run .circleci/generate.go .
      - run: diff  <(cat .circleci/config.yml) <(go run .circleci/generate.go .)

workflows:
  version: 2
  verify-test:
    jobs:
      - verify-circleci

      # bearertoken
      - godel/verify:
          name: bearertoken-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bearertoken
      - godel/test:
          name: bearertoken-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/bearertoken
          requires:
            - bearertoken-verify

      # binary
      - godel/verify:
          name: binary-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/binary
      - godel/test:
          name: binary-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/binary
          requires:
            - binary-verify

      # bytesbuffers
      - godel/verify:
          name: bytesbuffers-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bytesbuffers
      - godel/test:
          name: bytesbuffers-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/bytesbuffers
          requires:
            - bytesbuffers-verify

      # cli
      - godel/verify:
          name: cli-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/cli
      - godel/test:
          name: cli-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/cli
          requires:
            - cli-verify

      # cobracli
      - godel/verify:
          name: cobracli-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/cobracli
      - godel/test:
          name: cobracli-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/cobracli
          requires:
            - cobracli-verify

      # datetime
      - godel/verify:
          name: datetime-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/datetime
      - godel/test:
          name: datetime-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/datetime
          requires:
            - datetime-verify

      # gittest
      - godel/verify:
          name: gittest-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/gittest
      - godel/test:
          name: gittest-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/gittest
          requires:
            - gittest-verify

      # httpclient
      - godel/verify:
          name: httpclient-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/httpclient
      - godel/test:
          name: httpclient-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/httpclient
          requires:
            - httpclient-verify

      # httpserver
      - godel/verify:
          name: httpserver-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/httpserver
      - godel/test:
          name: httpserver-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/httpserver
          requires:
            - httpserver-verify

      # matcher
      - godel/verify:
          name: matcher-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/matcher
      - godel/test:
          name: matcher-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/matcher
          requires:
            - matcher-verify

      # merge
      - godel/verify:
          name: merge-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/merge
      - godel/test:
          name: merge-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/merge
          requires:
            - merge-verify

      # metrics
      - godel/verify:
          name: metrics-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/metrics
      - godel/test:
          name: metrics-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/metrics
          requires:
            - metrics-verify

      # objmatcher
      - godel/verify:
          name: objmatcher-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/objmatcher
      - godel/test:
          name: objmatcher-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/objmatcher
          requires:
            - objmatcher-verify

      # pkgpath
      - godel/verify:
          name: pkgpath-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/pkgpath
      - godel/test:
          name: pkgpath-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/pkgpath
          requires:
            - pkgpath-verify

      # retry
      - godel/verify:
          name: retry-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/retry
      - godel/test:
          name: retry-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/retry
          requires:
            - retry-verify

      # rid
      - godel/verify:
          name: rid-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/rid
      - godel/test:
          name: rid-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/rid
          requires:
            - rid-verify

      # safehttp
      - godel/verify:
          name: safehttp-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/safehttp
      - godel/test:
          name: safehttp-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/safehttp
          requires:
            - safehttp-verify

      # safejson
      - godel/verify:
          name: safejson-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/safejson
      - godel/test:
          name: safejson-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/safejson
          requires:
            - safejson-verify

      # safelong
      - godel/verify:
          name: safelong-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/safelong
      - godel/test:
          name: safelong-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/safelong
          requires:
            - safelong-verify

      # safeyaml
      - godel/verify:
          name: safeyaml-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/safeyaml
      - godel/test:
          name: safeyaml-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/safeyaml
          requires:
            - safeyaml-verify

      # signals
      - godel/verify:
          name: signals-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/signals
      - godel/test:
          name: signals-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/signals
          requires:
            - signals-verify

      # specdir
      - godel/verify:
          name: specdir-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/specdir
      - godel/test:
          name: specdir-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/specdir
          requires:
            - specdir-verify

      # tableprinter
      - godel/verify:
          name: tableprinter-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/tableprinter
      - godel/test:
          name: tableprinter-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/tableprinter
          requires:
            - tableprinter-verify

      # tlsconfig
      - godel/verify:
          name: tlsconfig-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/tlsconfig
      - godel/test:
          name: tlsconfig-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/tlsconfig
          requires:
            - tlsconfig-verify

      # transform
      - godel/verify:
          name: transform-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/transform
      - godel/test:
          name: transform-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/transform
          requires:
            - transform-verify

      # typenames
      - godel/verify:
          name: typenames-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/typenames
      - godel/test:
          name: typenames-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/typenames
          requires:
            - typenames-verify

      # uuid
      - godel/verify:
          name: uuid-verify
          <<: *checkout-path
          include-tests: true
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/uuid
      - godel/test:
          name: uuid-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/uuid
          requires:
            - uuid-verify
