checks:
  golint:
    filters:
    - value: should have comment or be unexported
    - value: or a comment on this block
    - value: error strings should not be capitalized or end with punctuation or a newline
  ineffassign:
    exclude:
      paths:
      - safeyaml/ghodss_yaml.go # Ignore safeyaml/ghodss_yaml.go:373:2: ineffectual assignment to count
