// Copyright (c) 2018 Palantir Technologies. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package datetime_test

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/palantir/pkg/datetime"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var dateTimeJSONs = []struct {
	sec        int64
	zoneOffset int
	str        string
	json       string
}{
	{
		sec:  1483326245,
		str:  `2017-01-02T03:04:05Z`,
		json: `"2017-01-02T03:04:05Z"`,
	},
	{
		sec:  1483326245,
		str:  `2017-01-02T03:04:05Z`,
		json: `"2017-01-02T03:04:05.000Z"`,
	},
	{
		sec:  1483326245,
		str:  `2017-01-02T03:04:05Z`,
		json: `"2017-01-02T03:04:05.000000000Z"`,
	},
	{
		sec:        1483326245,
		zoneOffset: 3600,
		str:        `2017-01-02T04:04:05+01:00`,
		json:       `"2017-01-02T04:04:05.000000000+01:00"`,
	},
	{
		sec:        1483326245,
		zoneOffset: 7200,
		str:        `2017-01-02T05:04:05+02:00`,
		json:       `"2017-01-02T05:04:05.000000000+02:00"`,
	},
	{
		sec:        1483326245,
		zoneOffset: 3600,
		str:        `2017-01-02T04:04:05+01:00`,
		json:       `"2017-01-02T04:04:05.000000000+01:00[Europe/Berlin]"`,
	},
}

func TestDateTimeString(t *testing.T) {
	for i, currCase := range dateTimeJSONs {
		currDateTime := datetime.DateTime(time.Unix(currCase.sec, 0).In(time.FixedZone("", currCase.zoneOffset)))
		assert.Equal(t, currCase.str, currDateTime.String(), "Case %d", i)
	}
}

func TestDateTimeMarshal(t *testing.T) {
	for i, currCase := range dateTimeJSONs {
		currDateTime := datetime.DateTime(time.Unix(currCase.sec, 0).In(time.FixedZone("", currCase.zoneOffset)))
		bytes, err := json.Marshal(currDateTime)
		require.NoError(t, err, "Case %d: marshal %q", i, currDateTime.String())

		var unmarshaledFromMarshal datetime.DateTime
		err = json.Unmarshal(bytes, &unmarshaledFromMarshal)
		require.NoError(t, err, "Case %d: unmarshal %q", i, string(bytes))

		var unmarshaledFromCase datetime.DateTime
		err = json.Unmarshal([]byte(currCase.json), &unmarshaledFromCase)
		require.NoError(t, err, "Case %d: unmarshal %q", i, currCase.json)

		assert.Equal(t, unmarshaledFromCase, unmarshaledFromMarshal, "Case %d", i)
	}
}

func TestDateTimeUnmarshal(t *testing.T) {
	for i, currCase := range dateTimeJSONs {
		wantDateTime := time.Unix(currCase.sec, 0).UTC()
		if currCase.zoneOffset != 0 {
			wantDateTime = wantDateTime.In(time.FixedZone("", currCase.zoneOffset))
		}

		var gotDateTime datetime.DateTime
		err := json.Unmarshal([]byte(currCase.json), &gotDateTime)
		require.NoError(t, err, "Case %d", i)

		assert.Equal(t, wantDateTime, time.Time(gotDateTime), "Case %d", i)
	}
}

// TestUnmarshalOffsetDateTimeToString verifies that the ISO 8601 representations generated by Java's OffsetDateTime's
// ToString method can be unmarshaled as a DateTime. Per the documentation at https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#toString--:
//
// The output will be one of the following ISO-8601 formats:
//
//   - uuuu-MM-dd'T'HH:mmXXXXX
//   - uuuu-MM-dd'T'HH:mm:ssXXXXX
//   - uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX
//   - uuuu-MM-dd'T'HH:mm:ss.SSSSSSXXXXX
//   - uuuu-MM-dd'T'HH:mm:ss.SSSSSSSSSXXXXX
//
// The format used will be the shortest that outputs the full value of the time where the omitted parts are implied to be zero.
//
// Test cases generated by Clauded based on the above.
func TestUnmarshalOffsetDateTimeToString(t *testing.T) {
	testCases := []struct {
		name   string
		input  string
		output string
	}{
		{
			name:   "uuuu-MM-dd'T'HH:mmXXXXX - Truncated seconds",
			input:  `"2019-03-26T14:30Z"`,
			output: `"2019-03-26T14:30:00Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ssXXXXX - With seconds",
			input:  `"2019-03-26T14:30:45Z"`,
			output: `"2019-03-26T14:30:45Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Milliseconds",
			input:  `"2019-03-26T14:00:00.123Z"`,
			output: `"2019-03-26T14:00:00.123Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSSSSXXXXX - Microseconds",
			input:  `"2019-03-26T14:00:00.123456Z"`,
			output: `"2019-03-26T14:00:00.123456Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSSSSSSSXXXXX - Nanoseconds",
			input:  `"2019-03-26T14:00:00.123456789Z"`,
			output: `"2019-03-26T14:00:00.123456789Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Single fractional digit padded to milliseconds",
			input:  `"2019-03-26T14:00:00.9Z"`,
			output: `"2019-03-26T14:00:00.9Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Two fractional digits padded to milliseconds",
			input:  `"2019-03-26T14:00:00.12Z"`,
			output: `"2019-03-26T14:00:00.12Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Four fractional digits truncated to milliseconds",
			input:  `"2019-03-26T14:00:00.4999Z"`,
			output: `"2019-03-26T14:00:00.4999Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Five fractional digits",
			input:  `"2019-03-26T14:00:00.12345Z"`,
			output: `"2019-03-26T14:00:00.12345Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSSSSXXXXX - Seven fractional digits",
			input:  `"2019-03-26T14:00:00.1234567Z"`,
			output: `"2019-03-26T14:00:00.1234567Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSSSSSSSXXXXX - Ten fractional digits truncated to nanoseconds",
			input:  `"2019-03-26T14:00:00.1234567899Z"`,
			output: `"2019-03-26T14:00:00.123456789Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Pre-epoch with fractional seconds",
			input:  `"1969-03-26T14:00:00.4999Z"`,
			output: `"1969-03-26T14:00:00.4999Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Timezone offset with milliseconds",
			input:  `"2019-03-26T14:00:00.123-07:00"`,
			output: `"2019-03-26T14:00:00.123-07:00"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ssXXXXX - Input without seconds normalized to include seconds",
			input:  `"2019-03-26T14:00:00Z"`,
			output: `"2019-03-26T14:00:00Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ssXXXXX - Zero subseconds omitted with non-zero seconds",
			input:  `"2019-03-26T14:00:30.000Z"`,
			output: `"2019-03-26T14:00:30Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Trailing zeros in milliseconds removed",
			input:  `"2019-03-26T14:00:00.100Z"`,
			output: `"2019-03-26T14:00:00.1Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSXXXXX - Trailing zeros in microseconds removed to milliseconds",
			input:  `"2019-03-26T14:00:00.123000Z"`,
			output: `"2019-03-26T14:00:00.123Z"`,
		},
		{
			name:   "uuuu-MM-dd'T'HH:mm:ss.SSSSSSXXXXX - Trailing zeros in nanoseconds removed to microseconds",
			input:  `"2019-03-26T14:00:00.123456000Z"`,
			output: `"2019-03-26T14:00:00.123456Z"`,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			var dt datetime.DateTime
			err := json.Unmarshal([]byte(tc.input), &dt)
			require.NoError(t, err, "Failed to unmarshal %s", tc.input)

			marshaled, err := json.Marshal(dt)
			require.NoError(t, err, "Failed to marshal datetime")

			assert.Equal(t, tc.output, string(marshaled))
		})
	}
}
