// Copyright (c) 2026 Palantir Technologies. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package codegenfiles_test

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/palantir/pkg/codegenfiles"
	"github.com/palantir/pkg/matcher"
)

// generate stands in for whatever a real generator does, returning the files it wants to exist keyed by
// path relative to the project directory.
func generate() map[string][]byte {
	const header = "// Code generated by example. DO NOT EDIT.\n\npackage gen\n"
	return map[string][]byte{
		filepath.Join("gen", "widget.go"): []byte(header + "// widget\n"),
		filepath.Join("gen", "gadget.go"): []byte(header + "// gadget\n"),
	}
}

// This example reconciles a generator's output against a directory that already holds output from an
// earlier run: one file is up to date, one is stale, and a hand-written file shares the directory.
func Example() {
	projectDir, err := os.MkdirTemp("", "codegenfiles-example-")
	if err != nil {
		panic(err)
	}
	defer func() {
		_ = os.RemoveAll(projectDir)
	}()

	// state left by an earlier run
	const header = "// Code generated by example. DO NOT EDIT.\n\npackage gen\n"
	mustWrite(filepath.Join(projectDir, "gen", "widget.go"), header+"// widget\n") // still current
	mustWrite(filepath.Join(projectDir, "gen", "sprocket.go"), header+"// old\n")  // no longer generated
	mustWrite(filepath.Join(projectDir, "gen", "helpers.go"), "package gen\n")     // written by a human

	out := codegenfiles.NewOutput()
	out.AddAll(generate())

	p := &codegenfiles.Project{
		Dir:             projectDir,
		FileMatcher:     matcher.Name(`.+\.go`),
		ContentsMatcher: codegenfiles.GeneratedCodeMatcher(),
		DeleteStale:     true,
	}
	changes, err := p.Plan(out)
	if err != nil {
		panic(err)
	}

	// Plan has not touched anything yet. A tool's verify mode reports here and stops.
	fmt.Println(changes)

	if err := changes.Apply(); err != nil {
		panic(err)
	}

	// Reconciling again finds nothing to do.
	changes, err = p.Plan(out)
	if err != nil {
		panic(err)
	}
	fmt.Printf("second run empty: %v\n", changes.Empty())

	// Output:
	// gen/gadget.go: missing
	// gen/sprocket.go: no longer generated
	// removing file gen/sprocket.go
	// second run empty: true
}

func mustWrite(path, content string) {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		panic(err)
	}
}
