// Copyright (c) 2026 Palantir Technologies. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package codegenfiles_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/palantir/pkg/codegenfiles"
	"github.com/palantir/pkg/matcher"
)

const generatedHeader = "// Code generated by test. DO NOT EDIT.\n\npackage gen\n"

func keptContent() []byte { return []byte(generatedHeader + "// kept\n") }

// newProject returns a Project that owns every .go file under dir and deletes stale generated ones.
func newProject(dir string) *codegenfiles.Project {
	return &codegenfiles.Project{
		Dir:             dir,
		FileMatcher:     matcher.Name(`.+\.go`),
		ContentsMatcher: codegenfiles.GeneratedCodeMatcher(),
		DeleteStale:     true,
	}
}

// outputWith returns an Output containing gen/kept.go with the standard content.
func outputWith(paths ...string) *codegenfiles.Output {
	out := codegenfiles.NewOutput()
	for _, p := range paths {
		out.Add(p, keptContent())
	}
	return out
}

func TestPlan_ReportsMissingOutOfDateAndStaleFiles(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "outdated.go"), generatedHeader+"// old\n")
	writeFile(t, filepath.Join(genDir, "stale.go"), generatedHeader+"// stale\n")
	writeFile(t, filepath.Join(genDir, "hand.go"), "package gen\n")

	out := outputWith(filepath.Join("gen", "outdated.go"), filepath.Join("gen", "created.go"))
	changes, err := newProject(projectDir).Plan(out)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}

	assertWrites(t, changes, map[string]bool{
		filepath.Join("gen", "created.go"):  true,  // does not exist yet
		filepath.Join("gen", "outdated.go"): false, // exists with different content
	})
	assertRemovals(t, changes, filepath.Join("gen", "stale.go")) // hand.go has no marker, so is preserved

	// Plan must not have touched the filesystem
	assertNotExists(t, filepath.Join(genDir, "created.go"))
	assertExists(t, filepath.Join(genDir, "stale.go"))
	assertContent(t, filepath.Join(genDir, "outdated.go"), generatedHeader+"// old\n")
}

func TestPlan_UpToDateDirectoryIsEmpty(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "kept.go"), string(keptContent()))

	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if !changes.Empty() {
		t.Errorf("expected no changes, got:\n%s", changes)
	}
	if err := changes.Err(); err != nil {
		t.Errorf("expected Err to be nil for an up-to-date project, got: %v", err)
	}
}

func TestApply_WritesDeletesAndPreserves(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "stale.go"), generatedHeader+"// stale\n")
	writeFile(t, filepath.Join(genDir, "hand.go"), "package gen\n")

	p := newProject(projectDir)
	changes, err := p.Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	assertContent(t, filepath.Join(genDir, "kept.go"), string(keptContent()))
	assertExists(t, filepath.Join(genDir, "hand.go"))
	assertNotExists(t, filepath.Join(genDir, "stale.go"))

	// applying twice must be a no-op: re-planning the same output finds nothing to do
	changes, err = p.Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("second Plan: %v", err)
	}
	if !changes.Empty() {
		t.Errorf("expected the second plan to be empty, got:\n%s", changes)
	}
}

// An unchanged file must not be rewritten. Rewriting churns modification times, which editors, file
// watchers and mtime-based tools react to. It does not affect the Go build cache, which keys on content.
func TestApply_LeavesUnchangedFilesAlone(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	keptPath := filepath.Join(genDir, "kept.go")
	writeFile(t, keptPath, string(keptContent()))

	before, err := os.Stat(keptPath)
	if err != nil {
		t.Fatal(err)
	}
	// ensure a rewrite would be observable in the modification time
	stale := before.ModTime().Add(-time.Hour)
	if err := os.Chtimes(keptPath, stale, stale); err != nil {
		t.Fatal(err)
	}

	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	after, err := os.Stat(keptPath)
	if err != nil {
		t.Fatal(err)
	}
	if !after.ModTime().Equal(stale) {
		t.Errorf("unchanged file was rewritten: mtime moved from %v to %v", stale, after.ModTime())
	}
}

// Removing the last file in a directory removes the directory too, all the way up to the project
// directory. Cleanup deliberately does not consult FileMatcher: it climbs only through directories that
// the removal itself emptied, and a matcher that selects files (matcher.Name(`.+\.go`) matches no
// directory at all) cannot describe which directories a project owns.
func TestApply_RemovesEveryDirectoryEmptiedByARemoval(t *testing.T) {
	projectDir := t.TempDir()
	nested := filepath.Join(projectDir, "gen", "api", "v1")
	mkdirAll(t, nested)
	writeFile(t, filepath.Join(nested, "stale.go"), generatedHeader+"// stale\n")

	changes, err := newProject(projectDir).Plan(codegenfiles.NewOutput())
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	assertNotExists(t, nested)
	assertNotExists(t, filepath.Join(projectDir, "gen", "api"))
	assertNotExists(t, filepath.Join(projectDir, "gen"))
	assertExists(t, projectDir) // the climb stops at the project directory
}

// A directory that still holds something after a removal is left alone, including when what it holds is
// a hand-written file that the removal deliberately preserved.
func TestApply_KeepsDirectoriesThatAreStillOccupied(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "stale.go"), generatedHeader+"// stale\n")
	writeFile(t, filepath.Join(genDir, "hand.go"), "package gen\n")

	changes, err := newProject(projectDir).Plan(codegenfiles.NewOutput())
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	assertNotExists(t, filepath.Join(genDir, "stale.go"))
	assertExists(t, filepath.Join(genDir, "hand.go"))
	assertExists(t, genDir)
}

// Output produced by one source must not be treated as stale because another source did not produce it.
// This is why everything written into a managed directory goes through a single Project.
func TestPlan_DoesNotRemoveOutputFromAnotherSource(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "a.go"), string(keptContent()))
	writeFile(t, filepath.Join(genDir, "b.go"), string(keptContent()))

	out := codegenfiles.NewOutput()
	out.Add(filepath.Join("gen", "a.go"), keptContent()) // source A
	out.AddAll(map[string][]byte{                        // source B
		filepath.Join("gen", "b.go"): keptContent(),
	})

	changes, err := newProject(projectDir).Plan(out)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if !changes.Empty() {
		t.Errorf("expected no changes, got:\n%s", changes)
	}
}

// conjure keys its output on absolute paths, so those must reconcile against the same relative key as
// the files on disk rather than being treated as new.
func TestPlan_NormalizesAbsolutePaths(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "a.go"), string(keptContent()))

	out := codegenfiles.NewOutput()
	out.Add(filepath.Join(projectDir, "gen", "a.go"), keptContent())

	changes, err := newProject(projectDir).Plan(out)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if !changes.Empty() {
		t.Errorf("absolute path was not normalized; got changes:\n%s", changes)
	}
}

// metric-schema merges several schema files into one output directory, where two schemas producing the
// same path would otherwise silently overwrite each other.
func TestPlan_DuplicatePathIsRejected(t *testing.T) {
	out := codegenfiles.NewOutput()
	out.Add(filepath.Join("gen", "dup.go"), keptContent())
	out.Add(filepath.Join("gen", "dup.go"), keptContent())

	_, err := newProject(t.TempDir()).Plan(out)
	if err == nil {
		t.Fatal("expected an error when the same path is produced twice, got nil")
	}
	if !strings.Contains(err.Error(), "more than once") {
		t.Errorf("error should describe the duplicate, got: %v", err)
	}
}

// The same path reached by different spellings is still the same path.
func TestPlan_DuplicateViaAbsoluteAndRelativePathIsRejected(t *testing.T) {
	projectDir := t.TempDir()
	out := codegenfiles.NewOutput()
	out.Add(filepath.Join("gen", "dup.go"), keptContent())
	out.Add(filepath.Join(projectDir, "gen", "dup.go"), keptContent())

	if _, err := newProject(projectDir).Plan(out); err == nil {
		t.Fatal("expected an error when a path is produced both relatively and absolutely, got nil")
	}
}

func TestPlan_EscapingPathIsRejected(t *testing.T) {
	for _, path := range []string{
		filepath.Join("..", "evil.go"),
		filepath.Join("gen", "..", "..", "evil.go"),
	} {
		out := codegenfiles.NewOutput()
		out.Add(path, keptContent())
		if _, err := newProject(t.TempDir()).Plan(out); err == nil {
			t.Errorf("expected an error for path %q escaping the project directory, got nil", path)
		}
	}
}

// A directory standing where a generated file must go is cleared by the removals Apply performs first,
// rather than failing the write as it did when writes came first.
func TestApply_ReplacesDirectoryLeftByAPreviousRun(t *testing.T) {
	projectDir := t.TempDir()
	// a previous run produced gen/kept.go as a directory containing generated files
	obsolete := filepath.Join(projectDir, "gen", "kept.go")
	mkdirAll(t, obsolete)
	writeFile(t, filepath.Join(obsolete, "old.go"), generatedHeader+"// old\n")

	p := newProject(projectDir)
	changes, err := p.Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	assertContent(t, filepath.Join(projectDir, "gen", "kept.go"), string(keptContent()))
}

func TestPlan_DeleteStaleDisabledIgnoresUngeneratedFiles(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "stale.go"), generatedHeader+"// stale\n")

	p := newProject(projectDir)
	p.DeleteStale = false

	changes, err := p.Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(changes.Removals()) != 0 {
		t.Errorf("expected no removals with DeleteStale disabled, got %v", changes.Removals())
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	assertExists(t, filepath.Join(genDir, "stale.go"))
}

func TestChanges_StringListsEveryChangeSortedByPath(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "b.go"), generatedHeader+"// old\n")
	writeFile(t, filepath.Join(genDir, "c.go"), generatedHeader+"// stale\n")

	out := outputWith(filepath.Join("gen", "a.go"), filepath.Join("gen", "b.go"))
	changes, err := newProject(projectDir).Plan(out)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}

	want := strings.Join([]string{
		filepath.Join("gen", "a.go") + ": missing",
		filepath.Join("gen", "b.go") + ": out of date",
		filepath.Join("gen", "c.go") + ": no longer generated",
	}, "\n")
	if got := changes.String(); got != want {
		t.Errorf("String() =\n%s\nwant:\n%s", got, want)
	}
}
