// Copyright (c) 2026 Palantir Technologies. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package codegenfiles_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/palantir/pkg/codegenfiles"
	"github.com/palantir/pkg/matcher"
)

// A nil FileMatcher matches every path, so combining it with DeleteStale would delete the whole project
// directory. The configuration must be rejected before anything is read or written.
func TestPlan_NilFileMatcherWithDeleteStaleIsRejected(t *testing.T) {
	projectDir := t.TempDir()
	writeFile(t, filepath.Join(projectDir, "README.md"), "hello\n")
	writeFile(t, filepath.Join(projectDir, "main.go"), "package main\n")

	p := &codegenfiles.Project{Dir: projectDir, DeleteStale: true}
	if _, err := p.Plan(outputWith(filepath.Join("gen", "kept.go"))); err == nil {
		t.Error("expected Plan to reject a nil FileMatcher with DeleteStale, got nil")
	}
	assertExists(t, filepath.Join(projectDir, "README.md"))
	assertExists(t, filepath.Join(projectDir, "main.go"))
}

// Without deletion there is nothing destructive about a nil FileMatcher, so it stays allowed.
func TestPlan_NilFileMatcherWithoutDeleteStaleIsAllowed(t *testing.T) {
	projectDir := t.TempDir()
	p := &codegenfiles.Project{Dir: projectDir}
	changes, err := p.Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	assertExists(t, filepath.Join(projectDir, "gen", "kept.go"))
}

func TestPlan_EmptyDirIsRejected(t *testing.T) {
	p := &codegenfiles.Project{FileMatcher: matcher.Name(`.+\.go`)}
	if _, err := p.Plan(outputWith(filepath.Join("gen", "kept.go"))); err == nil {
		t.Error("expected Plan to reject an empty Dir, got nil")
	}
}

// FileMatcher bounds the on-disk set that generated output is reconciled against, so a generated path
// outside it could never be reconciled: it would be reported as missing however up to date it was, and
// rewritten on every run.
func TestPlan_GeneratedPathOutsideFileMatcherIsRejected(t *testing.T) {
	projectDir := t.TempDir()
	mkdirAll(t, filepath.Join(projectDir, "gen"))
	// already on disk with exactly the content the caller produces
	writeFile(t, filepath.Join(projectDir, "gen", "kept.go"), string(keptContent()))

	// FileMatcher covers only zz_*.go, so it does not match gen/kept.go
	p := &codegenfiles.Project{
		Dir:             projectDir,
		FileMatcher:     matcher.Name(`zz_.*\.go`),
		ContentsMatcher: codegenfiles.GeneratedCodeMatcher(),
		DeleteStale:     true,
	}

	_, err := p.Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err == nil {
		t.Fatal("expected an error for a generated path outside FileMatcher, got nil")
	}
	if !strings.Contains(err.Error(), "FileMatcher") {
		t.Errorf("error should explain the FileMatcher mismatch, got: %v", err)
	}
}

func TestGeneratedCodeMatcher_LineEndings(t *testing.T) {
	m := codegenfiles.GeneratedCodeMatcher()
	for _, tc := range []struct {
		name     string
		contents string
		want     bool
	}{
		{"LF", "// Code generated by test. DO NOT EDIT.\n\npackage gen\n", true},
		{"CRLF", "// Code generated by test. DO NOT EDIT.\r\n\r\npackage gen\r\n", true},
		{"no trailing newline", "// Code generated by test. DO NOT EDIT.", true},
		{"marker not on its own line", "package gen // Code generated by test. DO NOT EDIT.\n", false},
		{"no marker", "package gen\n", false},
	} {
		if got := m.MatchFileContents([]byte(tc.contents)); got != tc.want {
			t.Errorf("%s: MatchFileContents = %v, want %v", tc.name, got, tc.want)
		}
	}
}

// End-to-end counterpart of the CRLF case: a stale generated file with CRLF endings must still be
// recognized as generated and removed, rather than accumulating forever.
func TestApply_DeletesStaleFileWithCRLFLineEndings(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "stale.go"), "// Code generated by test. DO NOT EDIT.\r\n\r\npackage gen\r\n")

	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	assertNotExists(t, filepath.Join(genDir, "stale.go"))
}

func TestChanges_ErrDescribesOutdatedAndStaleFiles(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "kept.go"), generatedHeader+"// out of date\n")
	writeFile(t, filepath.Join(genDir, "stale.go"), generatedHeader+"// stale\n")

	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}

	verifyErr := changes.Err()
	if verifyErr == nil {
		t.Fatal("expected Err to report a difference, got nil")
	}
	for _, want := range []string{"kept.go", "stale.go"} {
		if !strings.Contains(verifyErr.Error(), want) {
			t.Errorf("Err should mention %s, got: %v", want, verifyErr)
		}
	}
	// reporting must not modify anything
	assertExists(t, filepath.Join(genDir, "stale.go"))
	assertContent(t, filepath.Join(genDir, "kept.go"), generatedHeader+"// out of date\n")
}

func mkdirAll(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0755); err != nil {
		t.Fatal(err)
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func assertExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Errorf("expected %s to exist: %v", path, err)
	}
}

func assertNotExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("expected %s to be removed, stat err = %v", path, err)
	}
}

func assertContent(t *testing.T, path, want string) {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Errorf("expected to read %s: %v", path, err)
		return
	}
	if string(got) != want {
		t.Errorf("%s contents = %q, want %q", path, got, want)
	}
}

// assertWrites checks that changes contains exactly the given writes, keyed by path with the expected
// Created flag.
func assertWrites(t *testing.T, changes *codegenfiles.Changes, want map[string]bool) {
	t.Helper()
	got := make(map[string]bool)
	for _, w := range changes.Writes() {
		got[w.Path] = w.Created
	}
	if len(got) != len(want) {
		t.Errorf("writes = %v, want %v", got, want)
		return
	}
	for path, created := range want {
		gotCreated, ok := got[path]
		if !ok {
			t.Errorf("expected a write for %s, got %v", path, got)
			continue
		}
		if gotCreated != created {
			t.Errorf("%s: Created = %v, want %v", path, gotCreated, created)
		}
	}
}

func assertRemovals(t *testing.T, changes *codegenfiles.Changes, want ...string) {
	t.Helper()
	got := changes.Removals()
	if len(got) != len(want) {
		t.Errorf("removals = %v, want %v", got, want)
		return
	}
	for i, w := range want {
		if got[i] != w {
			t.Errorf("removals[%d] = %s, want %s", i, got[i], w)
		}
	}
}
