// Copyright (c) 2026 Palantir Technologies. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package codegenfiles_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/palantir/pkg/codegenfiles"
	"github.com/palantir/pkg/matcher"
)

// Replacing a file must not disturb its permissions. Writing through a temporary file makes this a real
// risk: the temporary starts at 0600 and carries whatever mode it is given into place.
func TestApply_PreservesPermissionsOfReplacedFiles(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	keptPath := filepath.Join(genDir, "kept.go")
	writeFile(t, keptPath, generatedHeader+"// old\n")
	if err := os.Chmod(keptPath, 0640); err != nil {
		t.Fatal(err)
	}

	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	assertContent(t, keptPath, string(keptContent()))
	info, err := os.Stat(keptPath)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0640 {
		t.Errorf("permissions of the replaced file = %v, want %v", got, os.FileMode(0640))
	}
}

func TestApply_CreatesNewFilesReadable(t *testing.T) {
	projectDir := t.TempDir()
	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	info, err := os.Stat(filepath.Join(projectDir, "gen", "kept.go"))
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0644 {
		t.Errorf("permissions of the created file = %v, want %v", got, os.FileMode(0644))
	}
}

// The temporary file that each write goes through must not survive the write.
func TestApply_LeavesNoTemporaryFilesBehind(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	writeFile(t, filepath.Join(genDir, "kept.go"), generatedHeader+"// old\n")

	changes, err := newProject(projectDir).Plan(outputWith(
		filepath.Join("gen", "kept.go"),
		filepath.Join("gen", "created.go"),
	))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	entries, err := os.ReadDir(genDir)
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	for _, name := range names {
		if strings.Contains(name, ".tmp") {
			t.Errorf("temporary file left behind: %s (directory contains %v)", name, names)
		}
	}
	if len(names) != 2 {
		t.Errorf("expected exactly the two generated files, got %v", names)
	}
}

// A write that cannot be completed must leave the previous contents intact rather than truncating the
// file, which is the property renaming into place buys over writing in place.
func TestApply_FailedWriteLeavesPreviousContentsIntact(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root ignores the directory permissions this test relies on to make the write fail")
	}
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)
	keptPath := filepath.Join(genDir, "kept.go")
	original := generatedHeader + "// original\n"
	writeFile(t, keptPath, original)

	changes, err := newProject(projectDir).Plan(outputWith(filepath.Join("gen", "kept.go")))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}

	// make the directory read-only so the temporary file cannot be created
	if err := os.Chmod(genDir, 0500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.Chmod(genDir, 0755)
	})

	if err := changes.Apply(); err == nil {
		t.Fatal("expected Apply to fail when the temporary file cannot be created, got nil")
	}
	assertContent(t, keptPath, original)
}

func TestGeneratedCodeMatcher_CommentSyntaxes(t *testing.T) {
	m := codegenfiles.GeneratedCodeMatcher()
	for _, tc := range []struct {
		name     string
		contents string
		want     bool
	}{
		{"go", "// Code generated by test. DO NOT EDIT.\n\npackage gen\n", true},
		{"hash", "# Code generated by test. DO NOT EDIT.\n\nkey: value\n", true},
		{"html", "<!-- Code generated by test. DO NOT EDIT. -->\n\n# Metrics\n", true},
		{"html no inner space", "<!-- Code generated by test. DO NOT EDIT.-->\n", true},
		{"hash CRLF", "# Code generated by test. DO NOT EDIT.\r\n", true},
		{"html CRLF", "<!-- Code generated by test. DO NOT EDIT. -->\r\n", true},
		{"marker not on its own line", "key: value # Code generated by test. DO NOT EDIT.\n", false},
		{"no comment delimiter", "Code generated by test. DO NOT EDIT.\n", false},
		{"no marker", "# a hand-written config\n\nkey: value\n", false},
	} {
		if got := m.MatchFileContents([]byte(tc.contents)); got != tc.want {
			t.Errorf("%s: MatchFileContents = %v, want %v", tc.name, got, tc.want)
		}
	}
}

// The metric-schema case: one project owns a directory holding generated Go and generated Markdown, so
// a single ContentsMatcher has to recognize both, and a hand-written file of either kind must survive.
func TestApply_ReconcilesMixedGoAndMarkdownOutput(t *testing.T) {
	projectDir := t.TempDir()
	genDir := filepath.Join(projectDir, "gen")
	mkdirAll(t, genDir)

	const mdHeader = "<!-- Code generated by test. DO NOT EDIT. -->\n"
	writeFile(t, filepath.Join(genDir, "stale.go"), generatedHeader+"// stale\n")
	writeFile(t, filepath.Join(genDir, "stale.md"), mdHeader+"stale docs\n")
	writeFile(t, filepath.Join(genDir, "README.md"), "# hand-written notes\n")

	out := codegenfiles.NewOutput()
	out.Add(filepath.Join("gen", "kept.go"), keptContent())
	out.Add(filepath.Join("gen", "kept.md"), []byte(mdHeader+"docs\n"))

	p := &codegenfiles.Project{
		Dir:             projectDir,
		FileMatcher:     matcher.Name(`.+\.(go|md)`),
		ContentsMatcher: codegenfiles.GeneratedCodeMatcher(),
		DeleteStale:     true,
	}
	changes, err := p.Plan(out)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if err := changes.Apply(); err != nil {
		t.Fatalf("Apply: %v", err)
	}

	assertExists(t, filepath.Join(genDir, "kept.go"))
	assertExists(t, filepath.Join(genDir, "kept.md"))
	assertNotExists(t, filepath.Join(genDir, "stale.go"))
	assertNotExists(t, filepath.Join(genDir, "stale.md")) // recognized as generated by its HTML comment
	assertExists(t, filepath.Join(genDir, "README.md"))   // no marker, so preserved
}
