// Copyright (c) 2026 Palantir Technologies. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package clipackager

import (
	"fmt"
	"os"
	"path/filepath"
)

// RunGenerate runs the logic that is suitable for a "go generate" file that fetches a particular version of a target
// file (typically a bundled CLI) and writes the fetched version in a Go file.
func RunGenerate(
	generatorName,
	generatorDirPath,
	versionFilePath,
	targetFileVersion,
	targetFilePath,
	targetFileURL string,
) error {
	newVersionFileContent := fmt.Sprintf(`// Code generated by the %s generator. DO NOT EDIT.
// To update this file, run the generator in %s.
package %s

const Version = "%s"
`, generatorName, generatorDirPath, filepath.Base(filepath.Dir(versionFilePath)), targetFileVersion)

	// if target path exists, check if version file is up-to-date. If it does not exist, always attempt download.
	if _, err := os.Stat(targetFilePath); err == nil {
		// version file exists and is in desired state: assume that all generated content is in desired state
		if currVersionFileContent, err := os.ReadFile(versionFilePath); err == nil && string(currVersionFileContent) == newVersionFileContent {
			return nil
		}
		// target file exists, but version file was not desired state: remove the target file to force download
		if err := os.Remove(targetFilePath); err != nil {
			return fmt.Errorf("failed to remove existing version file %q: %w", targetFilePath, err)
		}
	}

	if err := EnsureFileWithSHA256ChecksumExists(targetFilePath, targetFileURL, ""); err != nil {
		return err
	}

	if err := os.WriteFile(versionFilePath, []byte(newVersionFileContent), 0644); err != nil {
		return fmt.Errorf("failed to write version file %q: %w", versionFilePath, err)
	}
	return nil
}
